// GrammarSync.swift
// Downloads grammar.json from the configured URL and caches it to Documents/grammar.json.
//
// URL resolution: derives the grammar URL from the vocab URL (substituting grammar.json for
// vocab.json), since both files are published to the same Gist by publish.mjs. Falls back to
// a GRAMMAR_URL environment variable for overrides or standalone testing.

import Foundation

// MARK: - Codable types matching grammar.json

struct GrammarManifest: Codable {
    let generatedAt: String
    let sources: [String: GrammarSourceMeta]
    var topics: [String: GrammarTopic]   // keyed by prefixed ID e.g. "genki:potential-verbs"
}

struct GrammarSourceMeta: Codable {
    let name: String
    let type: String    // "textbook", "online", "book"
}

/// One grammar topic as stored in grammar.json.
/// Description fields (summary, subUses, cautions, isStub) are not stored in grammar.json —
/// they come from grammar-equivalences.json and are populated at sync time via
/// GrammarSync.mergeDescriptions(into:from:).
struct GrammarTopic: Codable {
    let source: String          // "genki" | "bunpro" | "dbjg"
    let id: String              // local (un-prefixed) slug, e.g. "potential-verbs"
    let titleEn: String         // English title, e.g. "Potential verbs"
    let titleJp: String?        // Japanese title (Bunpro only), e.g. "てならない"
    let level: String           // e.g. "Genki II", "jlptN4"
    let href: String?           // URL to external reference page
    let sources: [String]       // story/textbook sources this topic appears in
    let references: [String: [VocabReference]]?     // corpus occurrences keyed by source title
    let equivalenceGroup: [String]?  // other prefixed topic IDs in the same equivalence group

    // Populated from grammar-equivalences.json at sync time (not in grammar.json).
    var summary: String?              // one-paragraph description of the grammar point
    var subUses: [GrammarSubUse]?     // list of sub-uses, each with a stable id and description
    var cautions: [String]?           // common mistakes and edge cases
    var isStub: Bool?           // true if description was generated without any user content sentences
    var classicalJapanese: Bool?  // true if this topic covers a Classical Japanese grammar point

    /// The full source-prefixed identifier, e.g. "genki:potential-verbs".
    var prefixedId: String { "\(source):\(id)" }

    // Custom CodingKeys so description fields are excluded from Codable round-trips
    // (they aren't in grammar.json and we don't want encoding to include them).
    private enum CodingKeys: String, CodingKey {
        case source, id, titleEn, titleJp, level, href, sources, references, equivalenceGroup
    }
}

// MARK: - Equivalence group (grammar-equivalences.json)

/// One sub-use entry inside a grammar equivalence group.
/// The `id` is a stable slug derived at migration time from the first meaningful English words
/// of the description text (e.g. "casual-suggestion-or"). It never changes once assigned.
/// `text` is the full human-readable description including a Japanese example.
///
/// Decodes from either the legacy plain-string format or the current `{ "id": "...", "text": "..." }`
/// object format, so old cached grammar-equivalences.json files keep working after the migration.
struct GrammarSubUse: Codable, Equatable {
    let id: String      // stable slug, e.g. "casual-suggestion-or"
    let text: String    // full description with Japanese example

    init(id: String, text: String) {
        self.id = id
        self.text = text
    }

    init(from decoder: Decoder) throws {
        // Try object form first; fall back to plain string for legacy caches.
        if let container = try? decoder.container(keyedBy: CodingKeys.self) {
            id   = try container.decode(String.self, forKey: .id)
            text = try container.decode(String.self, forKey: .text)
        } else {
            let plain = try decoder.singleValueContainer().decode(String.self)
            text = plain
            // Derive a best-effort slug from the plain string (stable for the life of the cache).
            id = plain
                .split(separator: ":").first
                .map(String.init) ?? plain
        }
    }

    private enum CodingKeys: String, CodingKey { case id, text }
}

/// One equivalence group from grammar/grammar-equivalences.json.
/// Each group bundles one or more topic IDs that describe the same grammar point across
/// different databases, along with a human-readable description generated by the
/// /cluster-grammar-topics skill.
struct GrammarEquivalenceGroup: Codable {
    let topics: [String]              // prefixed topic IDs, e.g. ["genki:potential-verbs", "bunpro:られる-Potential"]
    let summary: String               // one-paragraph plain-English description of the grammar point
    let subUses: [GrammarSubUse]      // sub-use descriptions, each with a stable id and a Japanese example
    let cautions: [String]            // common mistakes and edge cases
    let stub: Bool?                   // true if generated without any user content sentences
    let classicalJapanese: Bool?      // true if this group covers a Classical Japanese grammar point
}

// MARK: - Sync helpers

enum GrammarSync {
    private static let cacheFilename = "grammar.json"
    private static let equivalencesCacheFilename = "grammar-equivalences.json"

    /// Resolve the grammar download URL.
    /// Priority:
    ///   1. Derive from vocab URL (replace "vocab.json" with "grammar.json")
    ///   2. GRAMMAR_URL environment variable
    static func resolvedURL() -> URL? { derivedURL(replacing: "grammar.json", fallbackEnvVar: "GRAMMAR_URL") }

    /// Download grammar.json from the resolved URL, decode it, and cache to Documents.
    /// Throws `GrammarSyncError.noURLConfigured` if no URL can be derived.
    @discardableResult
    static func sync() async throws -> GrammarManifest {
        guard let url = resolvedURL() else {
            throw GrammarSyncError.noURLConfigured
        }
        let (data, response) = try await URLSession.shared.data(for: authenticatedRequest(for: url))
        if let http = response as? HTTPURLResponse, http.statusCode != 200 {
            throw GrammarSyncError.httpError(http.statusCode)
        }
        let manifest = try JSONDecoder().decode(GrammarManifest.self, from: data)
        let cacheURL = try cacheFileURL()
        try data.write(to: cacheURL)
        print("[GrammarSync] synced \(manifest.topics.count) topic(s) → \(cacheURL.lastPathComponent)")
        return manifest
    }

    /// Load the cached grammar.json from Documents (nil if not yet downloaded).
    static func cached() -> GrammarManifest? {
        guard let url = try? cacheFileURL(),
              let data = try? Data(contentsOf: url),
              let manifest = try? JSONDecoder().decode(GrammarManifest.self, from: data)
        else { return nil }
        return manifest
    }

    private static func cacheFileURL() throws -> URL { try documentsURL(filename: cacheFilename) }

    // MARK: - Equivalences (grammar-equivalences.json)

    /// Resolve the equivalences download URL by substituting "grammar-equivalences.json" for
    /// "vocab.json" in the vocab URL.  Falls back to GRAMMAR_EQUIVALENCES_URL env var.
    static func equivalencesURL() -> URL? { derivedURL(replacing: "grammar-equivalences.json", fallbackEnvVar: "GRAMMAR_EQUIVALENCES_URL") }

    /// Download grammar-equivalences.json, decode it, and cache to Documents.
    @discardableResult
    static func syncEquivalences() async throws -> [GrammarEquivalenceGroup] {
        guard let url = equivalencesURL() else {
            throw GrammarSyncError.noURLConfigured
        }
        let (data, response) = try await URLSession.shared.data(for: authenticatedRequest(for: url))
        if let http = response as? HTTPURLResponse, http.statusCode != 200 {
            throw GrammarSyncError.httpError(http.statusCode)
        }
        let groups = try JSONDecoder().decode([GrammarEquivalenceGroup].self, from: data)
        let cacheURL = try equivalencesCacheFileURL()
        try data.write(to: cacheURL)
        print("[GrammarSync] synced \(groups.count) equivalence group(s) → \(cacheURL.lastPathComponent)")
        return groups
    }

    /// Load the cached grammar-equivalences.json from Documents (nil if not yet downloaded).
    static func cachedEquivalences() -> [GrammarEquivalenceGroup]? {
        guard let url = try? equivalencesCacheFileURL(),
              let data = try? Data(contentsOf: url),
              let groups = try? JSONDecoder().decode([GrammarEquivalenceGroup].self, from: data)
        else { return nil }
        return groups
    }

    /// Populate description fields on all topics in `manifest` from the given equivalence groups.
    /// Topics whose prefixed ID appears in an equivalence group gain summary, subUses, cautions,
    /// and isStub from that group.  Topics not in any group are left unchanged.
    static func mergeDescriptions(into manifest: inout GrammarManifest,
                                   from groups: [GrammarEquivalenceGroup]) {
        var groupByTopicId: [String: GrammarEquivalenceGroup] = [:]
        for group in groups {
            for topicId in group.topics {
                groupByTopicId[topicId] = group
            }
        }
        for key in manifest.topics.keys {
            guard let group = groupByTopicId[key] else { continue }
            manifest.topics[key]?.summary  = group.summary
            manifest.topics[key]?.subUses  = group.subUses
            manifest.topics[key]?.cautions = group.cautions
            manifest.topics[key]?.isStub          = group.stub
            manifest.topics[key]?.classicalJapanese = group.classicalJapanese
        }
    }

    private static func equivalencesCacheFileURL() throws -> URL { try documentsURL(filename: equivalencesCacheFilename) }
}

// MARK: - Errors

enum GrammarSyncError: Error, LocalizedError {
    case noURLConfigured
    case httpError(Int)

    var errorDescription: String? {
        switch self {
        case .noURLConfigured:
            return "No grammar URL could be derived. Ensure vocab URL is configured (japanquiz://setup deep link or VOCAB_URL environment variable) or set GRAMMAR_URL explicitly."
        case .httpError(let code):
            return "Grammar download failed: HTTP \(code)"
        }
    }
}
